language: java
jdk:
- openjdk8

branches:
  only:
  - master

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
- zip -r dmzing-server *
- mkdir -p deploy
- mv dmzing-server.zip deploy/dmzing-server.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: dmzing-s3
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  on:
    repo: team-walkD/DMZing-server
    branch: master

notifications:
  email:
    recipients:
    - chldbtjd2272@naver.com


